#!/usr/bin/env python3
"""
quality_filter.py — shared data-quality / exclusion logic for the Teen AI Survey.

CANONICAL SOURCE. Do not edit the vendored copies. Edit this file in the
project root ("AI Survey/quality_filter.py"), then re-run sync_qc.bat to push
identical copies into all consumers:
    - Teen AI Survey Analysis/scripts/quality_filter.py
    - survey_management/response_management/quality_filter.py
    - survey_management/payment_management/quality_filter.py

WHY THIS FILE EXISTS
    Both the analysis repo and the survey-management repo need the *same*
    definition of a low-quality response, and they are separate git repos. To
    keep one rule (not two that drift), the logic lives here, is vendored into
    both, and is regenerated by sync_qc.bat rather than hand-edited in place.

WHAT IT DOES NOT DO
    It does not decide policy. It emits, per respondent, a set of independent
    quality FLAGS plus a recommended exclusion boolean. Each consumer applies
    its own policy:
        - Analysis: drop rows where exclude_recommended is True.
        - Survey management: log quality, and (under IRB clearance) route
          exclude_recommended completers to a Hold bucket for review. Hold means
          "a human decides before paying"; Fraud (the consent blacklist) is the
          only never-pay bucket.

DESIGN
    - Standard library only (csv, json, re, math, statistics, argparse). Runs anywhere,
      no pandas/yaml required. A from_dataframe() helper is provided for repos
      that already hold a pandas frame.
    - Thresholds are ABSOLUTE and pre-set, not SD-based. Response-time
      distributions are right-skewed and the pilot n is tiny (single digits),
      so mean +/- k*SD is unstable and flags the wrong people. Per-page reading
      floors and an absolute total-duration floor are robust at any n.
    - All thresholds live in DEFAULT_THRESHOLDS below and can be overridden by
      passing a dict, or by a quality_config.json / quality_config.yaml beside
      this file. Tune them on real data, BEFORE looking at outcomes, and record
      the final values in QUALITY_CONTROL.md.

CLI
    python quality_filter.py path/to/export.csv [-o quality_report.csv]
    If no path is given, the most recent *.csv in ./ or ../data/ is used.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import statistics
import sys
from pathlib import Path


# ----------------------------------------------------------------------------
# Expected answers for the embedded instructed-response attention checks.
# Each is shown on a different survey branch, so a BLANK cell means "not shown",
# not "failed". (Mirrors scripts/attention_check_report.py in the analysis repo.)
# ----------------------------------------------------------------------------
ATTENTION_CHECKS = {
    "Q220": "Probably okay",        # hypothetical-school-AI branch (no school AI)
    "Q218": "Definitely not okay",  # shown to everyone (comfort-in-school block)
    "Q219": "Probably not okay",    # real-school-AI branch (has school AI)
}

# ----------------------------------------------------------------------------
# TUNE THESE on real data, before looking at outcomes. Record final values in
# QUALITY_CONTROL.md. Defaults are deliberately conservative (favor keeping a
# borderline respondent over dropping a real one).
# ----------------------------------------------------------------------------
DEFAULT_THRESHOLDS = {
    # --- speeding: absolute floors, never SD-based ---
    "total_duration_floor_sec": 180,   # whole multi-block survey faster than this is implausible
    "page_floor_sec": 2.0,             # a single page submitted faster than this = "too fast to read"
    "min_fast_pages_to_flag": 2,       # need >= this many too-fast pages to raise the speeding flag
                                       #   (one stray fast page is noise)
    # --- bot / automation signal ---
    "recaptcha_min": 0.7,              # Qualtrics reCAPTCHA v3 score; below this is suspicious
    "recaptcha_error_is_flag": True,   # Q_RecaptchaStatus == "error" raises its own flag (bot signal)
    # --- attention ---
    "attention_fail_min": 1,           # raise the attention flag at >= this many failed shown checks
    "hard_exclude_if_all_attention_failed": True,  # 0 passed of >=2 shown -> exclude regardless of other flags
    # --- straight-lining (same answer down a whole matrix) ---
    "min_items_for_straightline": 5,   # only judge matrices with >= this many ANSWERED items
                                       #   (uniform answers across a short grid are too plausible)
    "min_straightline_matrices_to_flag": 1,  # raise the flag at >= this many straight-lined matrices
    "straightline_groups": {},         # matrix name -> list of column codes; loaded from config.
                                       #   Attention-check columns are intentionally NOT listed here,
                                       #   so straight-lining and attention stay independent signals.
    # --- open-text content checks (the free-text "walk us through" boxes) ---
    "open_text_cols": ["Q62", "Q63"],  # free-text question short codes screened for content junk
    "duplicate_min_words": 7,          # a cross-respondent duplicate must be at least this substantive
    "duplicate_min_chars": 30,         #   (short collisions like "my own ai account" are NOT duplicates)
    "option_text": [                   # normalized answer-option text; echoes never count as duplicates
        "your own ai account",
        "your schools ai account",
        "an ai that keeps a record of your past work to give faster more personalized help",
        "an ai that keeps no record of your work so nothing about you is stored",
    ],
    "option_echo_jaccard": 0.6,        # token-overlap threshold for "this is basically an option"
    # --- fraud blacklist (read at the quality/analysis stage too) ---
    "fraud_blacklist_path": "",        # "" = auto-discover data/fraud_blacklist.csv near this file/export
    # --- standalone (HARD) exclusion signals: exclude on their own, no >=2 needed ---
    "hard_exclude_signals": [
        "gibberish", "cross_respondent_duplicate", "both_blank_finished",
        "llm_paste_format", "fraud_blacklist",
    ],
    # --- combination rule ---
    "exclude_min_flags": 2,            # exclude when >= this many INDEPENDENT flags trip
    "count_incomplete_toward_exclusion": False,  # incomplete is informational by default
}

# Column-name constants in the Qualtrics export (short-code header row).
COL_DURATION = "Duration (in seconds)"
COL_FINISHED = "Finished"
COL_PROGRESS = "Progress"
COL_RECAPTCHA = "Q_RecaptchaScore"
COL_RECAPTCHA_STATUS = "Q_RecaptchaStatus"
COL_IP = "IPAddress"
COL_RESPONSE_ID = "ResponseId"
ID_PREFERENCE = ("cid", "cid_f", "cid_q", "ResponseId")
PAGE_SUBMIT_SUFFIX = "_Page Submit"


# ============================================================================
# Config loading
# ============================================================================
def load_thresholds(overrides=None):
    """Return DEFAULT_THRESHOLDS, optionally overlaid with a config file and/or
    an explicit overrides dict. Config file (quality_config.json or .yaml beside
    this module) is read if present; YAML is read only if PyYAML is installed,
    otherwise it is skipped silently and defaults are used."""
    cfg = dict(DEFAULT_THRESHOLDS)
    here = Path(__file__).resolve().parent
    json_path = here / "quality_config.json"
    yaml_path = here / "quality_config.yaml"
    if json_path.exists():
        cfg.update(json.loads(json_path.read_text()))
    elif yaml_path.exists():
        try:
            import yaml  # optional
            loaded = yaml.safe_load(yaml_path.read_text()) or {}
            cfg.update(loaded)
        except Exception:
            pass  # no PyYAML -> fall back to embedded defaults
    if overrides:
        cfg.update(overrides)
    return cfg


# ============================================================================
# Loading a Qualtrics export (3 header rows) with the standard library
# ============================================================================
def load_qualtrics_csv(path):
    """Return (codes, rows) where codes is the short-variable header list and
    rows is a list of dicts keyed by code. Handles the 3-row Qualtrics export
    (short codes, question text, ImportId JSON); real responses start at row 3."""
    with open(path, newline="", encoding="utf-8-sig") as fh:
        grid = list(csv.reader(fh))
    if not grid:
        return [], []
    codes = grid[0]
    # Detect how many header rows to skip: row 1 is question text; row 2 is the
    # ImportId JSON row if present.
    start = 1
    if len(grid) > 1:
        start = 2
        if len(grid) > 2 and "ImportId" in ",".join(grid[2]):
            start = 3
    rows = [dict(zip(codes, r)) for r in grid[start:] if any(c.strip() for c in r)]
    return codes, rows


# ============================================================================
# Text helpers for the open-text content signals
# ============================================================================
_WS = re.compile(r"\s+")
_NONALNUM = re.compile(r"[^a-z0-9 ]")
_VOWEL = re.compile(r"[aeiou]", re.I)
_INDENT = re.compile(r"\n\s{2,}\S")          # newline then an indented sub-line
_DASH = re.compile("[\u2014\u2013]")          # em dash / en dash
_KEYBOARD = re.compile(r"(asdf|qwer|zxcv|hjkl|jkl;|fjfj|lkjlkj|sdfsdf)", re.I)


def _norm_text(t):
    """Lowercase, strip punctuation, collapse whitespace. Used for duplicate
    matching and option-echo detection."""
    return _WS.sub(" ", _NONALNUM.sub("", str(t).lower())).strip()


def is_gibberish(t):
    """True for keyboard mash / non-language strings. Teen typos and slang are
    NOT gibberish; this only fires on near-certain junk."""
    s = str(t).strip()
    if not s:
        return False
    body = s.replace(" ", "")
    letters = sum(c.isalpha() for c in s)
    if len(s) >= 4 and body and letters / len(body) < 0.4 and not any(c.isdigit() for c in s):
        return True
    if re.search(r"(.)\1{4,}", s):                       # same char run >= 5
        return True
    toks = [w for w in re.findall(r"[a-zA-Z]+", s) if len(w) >= 4]
    if toks and sum(1 for w in toks if not _VOWEL.search(w)) / len(toks) >= 0.6:
        return True
    if _KEYBOARD.search(s):
        return True
    return False


def looks_llm_paste(t):
    """True when a free-text answer carries markers a teen typing in a box does
    not produce: em/en dashes, or an indented sub-bullet ("Title\n    detail")."""
    s = str(t)
    return bool(_INDENT.search(s) or _DASH.search(s))


def _is_option_echo(norm_key, cfg):
    """True when a normalized answer is just (a paraphrase of) an answer-option.
    Such echoes are low-effort real teens, so they are excluded from the
    cross-respondent-duplicate signal."""
    opts = cfg.get("option_text", []) or []
    if norm_key in opts:
        return True
    ks = set(norm_key.split())
    if not ks:
        return False
    thr = cfg.get("option_echo_jaccard", 0.6)
    for o in opts:
        os_ = set(o.split())
        if not os_:
            continue
        union = len(ks | os_)
        if union and len(ks & os_) / union >= thr:
            return True
    return False


def compute_duplicate_flags(rows, codes, cfg):
    """Return (dup_ids, clusters).

    dup_ids: set of respondent ids that share an identical, substantive,
    NON-option-echo open-text answer with at least one OTHER respondent. This is
    the paste/farm signal. Natural short collisions and option restatements are
    excluded by design so a real teen is never held for it.

    clusters: {(col, normalized_text): [sorted respondent ids]} for QA/audit."""
    cols = [c for c in cfg.get("open_text_cols", []) if c in codes]
    min_w = cfg.get("duplicate_min_words", 7)
    min_c = cfg.get("duplicate_min_chars", 30)
    buckets = {}
    for row in rows:
        rid = respondent_id(row)
        for c in cols:
            raw = str(row.get(c, "")).strip()
            if not raw:
                continue
            key = _norm_text(raw)
            if len(key) < min_c or len(key.split()) < min_w:
                continue
            if _is_option_echo(key, cfg):
                continue
            buckets.setdefault((c, key), []).append(rid)
    dup_ids = set()
    clusters = {}
    for (c, key), ids in buckets.items():
        distinct = sorted(set(ids))
        if len(distinct) > 1:
            dup_ids |= set(distinct)
            clusters[(c, key)] = distinct
    return dup_ids, clusters


def load_fraud_blacklist(path=None, base=None):
    """Return (ids, ips) read from a fraud_blacklist.csv if one is discoverable.
    Opt-in: empty sets when no file is found, so the filter stays a pure quality
    screen. Columns: response_id (= consent cid) and ip."""
    ids, ips = set(), set()
    candidates = []
    if path:
        candidates.append(Path(path))
    here = Path(__file__).resolve().parent
    bases = [here, here.parent]
    if base:
        bases += [Path(base), Path(base).parent]
    for b in bases:
        candidates.append(Path(b) / "data" / "fraud_blacklist.csv")
        candidates.append(Path(b) / "fraud_blacklist.csv")
    for c in candidates:
        try:
            if c and c.exists():
                with open(c, newline="", encoding="utf-8-sig") as fh:
                    for d in csv.DictReader(fh):
                        rid = str(d.get("response_id", "")).strip()
                        ip = str(d.get("ip", "")).strip()
                        if rid:
                            ids.add(rid)
                        if ip:
                            ips.add(ip)
                break
        except Exception:
            continue
    return ids, ips


# ============================================================================
# Core evaluation
# ============================================================================
def _to_float(val):
    try:
        return float(str(val).strip())
    except (TypeError, ValueError):
        return None


def respondent_id(row):
    for col in ID_PREFERENCE:
        val = str(row.get(col, "")).strip()
        if val:
            return val
    return "(unknown)"


def _page_submit_cols(codes):
    return [c for c in codes if c.endswith(PAGE_SUBMIT_SUFFIX)]


def evaluate_row(row, codes, cfg, dup_ids=None, fraud_ids=None, fraud_ips=None):
    """Return one flat dict of quality flags + an exclusion recommendation for a
    single response row (dict keyed by Qualtrics short code).

    dup_ids / fraud_ids / fraud_ips are cross-row sets computed once over the
    whole export (see evaluate_export / from_dataframe) and passed in."""
    dup_ids = dup_ids or set()
    fraud_ids = fraud_ids or set()
    fraud_ips = fraud_ips or set()

    res = {
        "id": respondent_id(row),
        "response_id": str(row.get(COL_RESPONSE_ID, "")).strip(),
    }

    # --- completeness ---
    finished_raw = str(row.get(COL_FINISHED, "")).strip().lower()
    finished = finished_raw in ("true", "1", "yes")
    progress = _to_float(row.get(COL_PROGRESS))
    res["finished"] = finished
    res["progress"] = progress

    # --- attention ---
    shown = passed = failed = 0
    fail_detail = []
    for col, expected in ATTENTION_CHECKS.items():
        ans = str(row.get(col, "")).strip()
        if ans == "":
            continue  # not shown on this branch
        shown += 1
        if ans.lower() == expected.lower():
            passed += 1
        else:
            failed += 1
            fail_detail.append(f"{col}: expected '{expected}', got '{ans}'")
    res["att_shown"] = shown
    res["att_passed"] = passed
    res["att_failed"] = failed
    flag_attention = failed >= cfg["attention_fail_min"]
    all_attention_failed = shown >= 2 and passed == 0

    # --- speeding ---
    duration = _to_float(row.get(COL_DURATION))
    res["duration_sec"] = duration
    speeding_total = duration is not None and duration < cfg["total_duration_floor_sec"]

    fast_pages = []
    for col in _page_submit_cols(codes):
        t = _to_float(row.get(col))
        if t is not None and 0 < t < cfg["page_floor_sec"]:
            fast_pages.append(col.replace(PAGE_SUBMIT_SUFFIX, ""))
    res["fast_pages_count"] = len(fast_pages)
    res["fast_pages"] = ";".join(fast_pages)
    speeding_pages = len(fast_pages) >= cfg["min_fast_pages_to_flag"]
    flag_speeding = bool(speeding_total or speeding_pages)

    # --- straight-lining: same answer down a whole matrix ---
    straightlined = []
    for name, cols in cfg.get("straightline_groups", {}).items():
        answers = [str(row.get(c, "")).strip() for c in cols]
        answers = [a for a in answers if a != ""]   # blanks = not shown / skipped
        if len(answers) >= cfg["min_items_for_straightline"] and len(set(answers)) == 1:
            straightlined.append(name)
    res["straightline_count"] = len(straightlined)
    res["straightlined"] = ";".join(straightlined)
    flag_straightlining = len(straightlined) >= cfg["min_straightline_matrices_to_flag"]

    # --- bot / automation: numeric reCAPTCHA score and error status ---
    recaptcha = _to_float(row.get(COL_RECAPTCHA))
    res["recaptcha"] = recaptcha
    flag_recaptcha = recaptcha is not None and recaptcha < cfg["recaptcha_min"]
    recaptcha_status = str(row.get(COL_RECAPTCHA_STATUS, "")).strip().lower()
    res["recaptcha_status"] = recaptcha_status
    flag_recaptcha_error = bool(cfg.get("recaptcha_error_is_flag", True)) and recaptcha_status == "error"

    # --- open-text content signals (free-text "walk us through" boxes) ---
    otc = [c for c in cfg.get("open_text_cols", []) if c in codes]
    ot_vals = [str(row.get(c, "")).strip() for c in otc]
    flag_gibberish = any(is_gibberish(v) for v in ot_vals if v)
    flag_llm_paste = any(looks_llm_paste(v) for v in ot_vals)
    flag_both_blank = bool(otc) and all(v == "" for v in ot_vals) and finished
    flag_cross_dup = res["id"] in dup_ids
    res["open_text_blank"] = bool(otc) and all(v == "" for v in ot_vals)

    # --- fraud blacklist (consent cid or survey IP) ---
    survey_ip = str(row.get(COL_IP, "")).strip()
    flag_fraud_blacklist = (res["id"] in fraud_ids) or bool(survey_ip and survey_ip in fraud_ips)

    # --- incomplete (informational unless configured) ---
    flag_incomplete = not finished

    res["flag_attention"] = flag_attention
    res["flag_speeding"] = flag_speeding
    res["flag_straightlining"] = flag_straightlining
    res["flag_recaptcha"] = flag_recaptcha
    res["flag_recaptcha_error"] = flag_recaptcha_error
    res["flag_gibberish"] = flag_gibberish
    res["flag_llm_paste"] = flag_llm_paste
    res["flag_both_blank"] = flag_both_blank
    res["flag_cross_dup"] = flag_cross_dup
    res["flag_fraud_blacklist"] = flag_fraud_blacklist
    res["flag_incomplete"] = flag_incomplete

    counted = [
        flag_attention, flag_speeding, flag_straightlining, flag_recaptcha,
        flag_recaptcha_error, flag_gibberish, flag_llm_paste, flag_both_blank,
        flag_cross_dup, flag_fraud_blacklist,
    ]
    if cfg["count_incomplete_toward_exclusion"]:
        counted.append(flag_incomplete)
    n_flags = sum(bool(x) for x in counted)
    res["n_flags"] = n_flags

    exclude = n_flags >= cfg["exclude_min_flags"]
    if cfg["hard_exclude_if_all_attention_failed"] and all_attention_failed:
        exclude = True

    # Standalone HARD signals: near-certain junk, exclude on their own.
    hard_map = {
        "gibberish": flag_gibberish,
        "cross_respondent_duplicate": flag_cross_dup,
        "both_blank_finished": flag_both_blank,
        "llm_paste_format": flag_llm_paste,
        "fraud_blacklist": flag_fraud_blacklist,
        "recaptcha_error": flag_recaptcha_error,
    }
    hard_hits = [name for name in cfg.get("hard_exclude_signals", []) if hard_map.get(name)]
    if hard_hits:
        exclude = True
    res["hard_exclude_hits"] = ";".join(hard_hits)
    res["exclude_recommended"] = exclude

    reasons = []
    if flag_attention:
        reasons.append(f"attention({failed}/{shown} failed)")
    if speeding_total:
        reasons.append(f"speeding_total({duration}s<{cfg['total_duration_floor_sec']}s)")
    if speeding_pages:
        reasons.append(f"speeding_pages({len(fast_pages)})")
    if flag_straightlining:
        reasons.append(f"straightlining({res['straightlined']})")
    if flag_recaptcha:
        reasons.append(f"recaptcha({recaptcha}<{cfg['recaptcha_min']})")
    if flag_recaptcha_error:
        reasons.append("recaptcha_error")
    if flag_gibberish:
        reasons.append("gibberish")
    if flag_llm_paste:
        reasons.append("llm_paste_format")
    if flag_both_blank:
        reasons.append("both_blank_finished")
    if flag_cross_dup:
        reasons.append("cross_respondent_duplicate")
    if flag_fraud_blacklist:
        reasons.append("fraud_blacklist")
    if flag_incomplete:
        reasons.append("incomplete")
    if cfg["hard_exclude_if_all_attention_failed"] and all_attention_failed:
        reasons.append("ALL_attention_failed")
    res["reasons"] = "; ".join(reasons)
    res["fail_detail"] = "; ".join(fail_detail)
    return res


def evaluate_export(path, overrides=None, fraud_ids=None, fraud_ips=None):
    """Evaluate every response in a Qualtrics CSV. Returns (records, cfg).
    Cross-row signals (duplicate clustering, fraud blacklist) are computed once
    over the whole export before the per-row pass."""
    cfg = load_thresholds(overrides)
    codes, rows = load_qualtrics_csv(path)
    dup_ids, _clusters = compute_duplicate_flags(rows, codes, cfg)
    if fraud_ids is None and fraud_ips is None:
        fraud_ids, fraud_ips = load_fraud_blacklist(
            cfg.get("fraud_blacklist_path"), base=Path(path).resolve().parent)
    records = [evaluate_row(row, codes, cfg, dup_ids, fraud_ids, fraud_ips) for row in rows]
    return records, cfg


def from_dataframe(df, overrides=None, fraud_ids=None, fraud_ips=None):
    """Convenience for repos that already hold a pandas DataFrame of the export
    (short-code columns, data rows only). Returns a list of record dicts.
    Add the result back with: df['exclude_recommended'] = [r['exclude_recommended'] ...]."""
    cfg = load_thresholds(overrides)
    codes = list(df.columns)
    rows = []
    for rec in df.to_dict("records"):
        row = {}
        for k, v in rec.items():
            if v is None or (isinstance(v, float) and math.isnan(v)):
                row[k] = ""
            else:
                row[k] = str(v)
        rows.append(row)
    dup_ids, _clusters = compute_duplicate_flags(rows, codes, cfg)
    if fraud_ids is None and fraud_ips is None:
        fraud_ids, fraud_ips = load_fraud_blacklist(cfg.get("fraud_blacklist_path"))
    return [evaluate_row(row, codes, cfg, dup_ids, fraud_ids, fraud_ips) for row in rows]


# ============================================================================
# Reporting / CLI
# ============================================================================
FIELDNAMES = [
    "id", "response_id", "finished", "progress", "duration_sec",
    "recaptcha", "recaptcha_status",
    "att_shown", "att_passed", "att_failed",
    "fast_pages_count", "fast_pages",
    "straightline_count", "straightlined",
    "open_text_blank",
    "flag_attention", "flag_speeding", "flag_straightlining", "flag_recaptcha",
    "flag_recaptcha_error", "flag_gibberish", "flag_llm_paste", "flag_both_blank",
    "flag_cross_dup", "flag_fraud_blacklist", "flag_incomplete",
    "n_flags", "hard_exclude_hits", "exclude_recommended", "reasons", "fail_detail",
]


def write_report(records, out_path):
    with open(out_path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDNAMES)
        w.writeheader()
        for r in records:
            w.writerow({k: r.get(k, "") for k in FIELDNAMES})


def print_summary(records, cfg):
    n = len(records)
    excl = [r for r in records if r["exclude_recommended"]]
    print("=" * 72)
    print("DATA-QUALITY / EXCLUSION REPORT")
    print("=" * 72)
    print(f"Respondents: {n}")
    print(f"Recommended exclusions: {len(excl)}  "
          f"(rule: >= {cfg['exclude_min_flags']} independent flags, "
          f"or all shown attention checks failed)")
    print("-" * 72)
    hdr = f"{'id':<20}{'dur':>6}{'att':>8}{'fast':>5}{'SL':>4}{'flags':>6}  excl  reasons"
    print(hdr)
    print("-" * 78)
    for r in records:
        att = f"{r['att_passed']}/{r['att_shown']}"
        dur = "" if r["duration_sec"] is None else int(r["duration_sec"])
        mark = "EXCL" if r["exclude_recommended"] else "  -"
        print(f"{r['id']:<20}{str(dur):>6}{att:>8}{r['fast_pages_count']:>5}"
              f"{r['straightline_count']:>4}{r['n_flags']:>6}  {mark}  {r['reasons']}")
    print()


def _find_default_csv():
    for cand_dir in (Path.cwd(), Path(__file__).resolve().parent,
                     Path(__file__).resolve().parent.parent / "data"):
        csvs = sorted(Path(cand_dir).glob("*.csv")) if cand_dir.exists() else []
        if csvs:
            return csvs[-1]
    sys.exit("No CSV found. Pass a path explicitly.")


def main():
    ap = argparse.ArgumentParser(description="Teen AI Survey data-quality filter.")
    ap.add_argument("csv", nargs="?", help="Qualtrics export CSV (3 header rows).")
    ap.add_argument("-o", "--out", default="quality_report.csv",
                    help="Where to write the per-respondent report CSV.")
    args = ap.parse_args()

    path = Path(args.csv) if args.csv else _find_default_csv()
    print(f"Reading: {path}\n")
    records, cfg = evaluate_export(path)
    print_summary(records, cfg)
    try:
        write_report(records, args.out)
        print(f"Wrote report -> {args.out}")
    except PermissionError:
        print(f"(Could not write {args.out} - file is open/locked. Close and re-run.)")


if __name__ == "__main__":
    main()
